export const navigation = [
{name: "1. Al-Fatihah (Pembukaan)", slug: "al-fatihah"},
{name: "2. Al-Baqarah (Sapi)", slug: "al-baqarah"},
{name: "3. Ali 'Imran (Keluarga Imran)", slug: "ali-imran"},
{name: "4. An-Nisa' (Wanita)", slug: "an-nisa"},
{name: "5. Al-Ma'idah (Hidangan)", slug: "al-ma-idah"},
{name: "6. Al-An'am (Binatang Ternak)", slug: "al-an-am"},
{name: "7. Al-A'raf (Tempat Tertinggi)", slug: "al-a-raf"},
{name: "8. Al-Anfal (Rampasan Perang)", slug: "al-anfal"},
{name: "9. At-Taubah (Pengampunan)", slug: "at-taubah"},
{name: "10. Yunus (Yunus)", slug: "yunus"},
{name: "11. Hud (Hud)", slug: "hud"},
{name: "12. Yusuf (Yusuf)", slug: "yusuf"},
{name: "13. Ar-Ra'd (Guruh)", slug: "ar-ra-d"},
{name: "14. Ibrahim (Ibrahim)", slug: "ibrahim"},
{name: "15. Al-Hijr (Hijr)", slug: "al-hijr"},
{name: "16. An-Nahl (Lebah)", slug: "an-nahl"},
{name: "17. Al-Isra' (Memperjalankan Malam Hari)", slug: "al-isra"},
{name: "18. Al-Kahf (Goa)", slug: "al-kahf"},
{name: "19. Maryam (Maryam)", slug: "maryam"},
{name: "20. Taha (Taha)", slug: "taha"},
{name: "21. Al-Anbiya' (Para Nabi)", slug: "al-anbiya"},
{name: "22. Al-Hajj (Haji)", slug: "al-hajj"},
{name: "23. Al-Mu'minun (Orang-Orang Mukmin)", slug: "al-mu-minun"},
{name: "24. An-Nur (Cahaya)", slug: "an-nur"},
{name: "25. Al-Furqan (Pembeda)", slug: "al-furqan"},
{name: "26. Asy-Syu'ara' (Para Penyair)", slug: "asy-syu-ara"},
{name: "27. An-Naml (Semut-semut)", slug: "an-naml"},
{name: "28. Al-Qasas (Kisah-Kisah)", slug: "al-qasas"},
{name: "29. Al-'Ankabut (Laba-Laba)", slug: "al-ankabut"},
{name: "30. Ar-Rum (Romawi)", slug: "ar-rum"},
{name: "31. Luqman (Luqman)", slug: "luqman"},
{name: "32. As-Sajdah (Sajdah)", slug: "as-sajdah"},
{name: "33. Al-Ahzab (Golongan Yang Bersekutu)", slug: "al-ahzab"},
{name: "34. Saba' (Saba')", slug: "saba"},
{name: "35. Fatir (Maha Pencipta)", slug: "fatir"},
{name: "36. Yasin (Yasin)", slug: "yasin"},
{name: "37. As-Saffat (Barisan-Barisan)", slug: "as-saffat"},
{name: "38. Sad (Sad)", slug: "sad"},
{name: "39. Az-Zumar (Rombongan)", slug: "az-zumar"},
{name: "40. Gafir (Maha Pengampun)", slug: "gafir"},
{name: "41. Fussilat (Yang Dijelaskan)", slug: "fussilat"},
{name: "42. Asy-Syura (Musyawarah)", slug: "asy-syura"},
{name: "43. Az-Zukhruf (Perhiasan)", slug: "az-zukhruf"},
{name: "44. Ad-Dukhan (Kabut)", slug: "ad-dukhan"},
{name: "45. Al-Jasiyah (Berlutut)", slug: "al-jasiyah"},
{name: "46. Al-Ahqaf (Bukit Pasir)", slug: "al-ahqaf"},
{name: "47. Muhammad (Muhammad)", slug: "muhammad"},
{name: "48. Al-Fath (Kemenangan)", slug: "al-fath"},
{name: "49. Al-Hujurat (Kamar-Kamar)", slug: "al-hujurat"},
{name: "50. Qaf (Qaf)", slug: "qaf"},
{name: "51. Az-Zariyat (Angin yang Menerbangkan)", slug: "az-zariyat"},
{name: "52. At-Tur (Bukit Tursina)", slug: "at-tur"},
{name: "53. An-Najm (Bintang)", slug: "an-najm"},
{name: "54. Al-Qamar (Bulan)", slug: "al-qamar"},
{name: "55. Ar-Rahman (Maha Pengasih)", slug: "ar-rahman"},
{name: "56. Al-Waqi'ah (Hari Kiamat)", slug: "al-waqi-ah"},
{name: "57. Al-Hadid (Besi)", slug: "al-hadid"},
{name: "58. Al-Mujadalah (Gugatan)", slug: "al-mujadalah"},
{name: "59. Al-Hasyr (Pengusiran)", slug: "al-hasyr"},
{name: "60. Al-Mumtahanah (Wanita Yang Diuji)", slug: "al-mumtahanah"},
{name: "61. As-Saff (Barisan)", slug: "as-saff"},
{name: "62. Al-Jumu'ah (Jumat)", slug: "al-jumu-ah"},
{name: "63. Al-Munafiqun (Orang-Orang Munafik)", slug: "al-munafiqun"},
{name: "64. At-Tagabun (Pengungkapan Kesalahan)", slug: "at-tagabun"},
{name: "65. At-Talaq (Talak)", slug: "at-talaq"},
{name: "66. At-Tahrim (Pengharaman)", slug: "at-tahrim"},
{name: "67. Al-Mulk (Kerajaan)", slug: "al-mulk"},
{name: "68. Al-Qalam (Pena)", slug: "al-qalam"},
{name: "69. Al-Haqqah (Hari Kiamat)", slug: "al-haqqah"},
{name: "70. Al-Ma'arij (Tempat Naik)", slug: "al-ma-arij"},
{name: "71. Nuh (Nuh)", slug: "nuh"},
{name: "72. Al-Jinn (Jin)", slug: "al-jinn"},
{name: "73. Al-Muzzammil (Orang Yang Berselimut)", slug: "al-muzzammil"},
{name: "74. Al-Muddassir (Orang Yang Berkemul)", slug: "al-muddassir"},
{name: "75. Al-Qiyamah (Hari Kiamat)", slug: "al-qiyamah"},
{name: "76. Al-Insan (Manusia)", slug: "al-insan"},
{name: "77. Al-Mursalat (Malaikat Yang Diutus)", slug: "al-mursalat"},
{name: "78. An-Naba' (Berita Besar)", slug: "an-naba"},
{name: "79. An-Nazi'at (Malaikat Yang Mencabut)", slug: "an-nazi-at"},
{name: "80. 'Abasa (Bermuka Masam)", slug: "abasa"},
{name: "81. At-Takwir (Penggulungan)", slug: "at-takwir"},
{name: "82. Al-Infitar (Terbelah)", slug: "al-infitar"},
{name: "83. Al-Mutaffifin (Orang-Orang Curang)", slug: "al-mutaffifin"},
{name: "84. Al-Insyiqaq (Terbelah)", slug: "al-insyiqaq"},
{name: "85. Al-Buruj (Gugusan Bintang)", slug: "al-buruj"},
{name: "86. At-Tariq (Yang Datang Di Malam Hari)", slug: "at-tariq"},
{name: "87. Al-A'la (Maha Tinggi)", slug: "al-a-la"},
{name: "88. Al-Gasyiyah (Hari Kiamat)", slug: "al-gasyiyah"},
{name: "89. Al-Fajr (Fajar)", slug: "al-fajr"},
{name: "90. Al-Balad (Negeri)", slug: "al-balad"},
{name: "91. Asy-Syams (Matahari)", slug: "asy-syams"},
{name: "92. Al-Lail (Malam)", slug: "al-lail"},
{name: "93. Ad-Duha (Duha)", slug: "ad-duha"},
{name: "94. Asy-Syarh (Lapang)", slug: "asy-syarh"},
{name: "95. At-Tin (Buah Tin)", slug: "at-tin"},
{name: "96. Al-'Alaq (Segumpal Darah)", slug: "al-alaq"},
{name: "97. Al-Qadr (Kemuliaan)", slug: "al-qadr"},
{name: "98. Al-Bayyinah (Bukti Nyata)", slug: "al-bayyinah"},
{name: "99. Az-Zalzalah (Guncangan)", slug: "az-zalzalah"},
{name: "100. Al-'Adiyat (Kuda Yang Berlari Kencang)", slug: "al-adiyat"},
{name: "101. Al-Qari'ah (Hari Kiamat)", slug: "al-qari-ah"},
{name: "102. At-Takasur (Bermegah-Megahan)", slug: "at-takasur"},
{name: "103. Al-'Asr (Asar)", slug: "al-asr"},
{name: "104. Al-Humazah (Pengumpat)", slug: "al-humazah"},
{name: "105. Al-Fil (Gajah)", slug: "al-fil"},
{name: "106. Quraisy (Quraisy)", slug: "quraisy"},
{name: "107. Al-Ma'un (Barang Yang Berguna)", slug: "al-ma-un"},
{name: "108. Al-Kausar (Pemberian Yang Banyak)", slug: "al-kausar"},
{name: "109. Al-Kafirun (Orang-Orang kafir)", slug: "al-kafirun"},
{name: "110. An-Nasr (Pertolongan)", slug: "an-nasr"},
{name: "111. Al-Lahab (Api Yang Bergejolak)", slug: "al-lahab"},
{name: "112. Al-Ikhlas (Ikhlas)", slug: "al-ikhlas"},
{name: "113. Al-Falaq (Subuh)", slug: "al-falaq"},
{name: "114. An-Nas (Manusia)", slug: "an-nas"},
]